---
- hosts: all

- name: Include dynamic variables
  import_playbook: ../static-assignments/common.yml 
  include: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- name: uat-webservers
- import_playbook: ../static-assignments/uat-webservers.yml

- name: Loadbalancers assignment
  import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required 

- name: import database file
  import_playbook: ../static-assignments/database.yml
  

